version: '3.1'

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./api:/var/www/test-task.loc
    ports:
      - "8080:80"

  php:
    build: ./api
    restart: always
    volumes:
      - ./api:/var/www/test-task.loc

  node:
    build: ./client
    restart: always
    ports:
      - "8008:8000"
    tty: true