version: '3.1'

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./api:/var/www/test-task.loc
    ports:
      - "8080:80"

  php:
    build: ./php
    restart: always
    volumes:
      - ./api:/var/www/test-task.loc

  node:
    image: node:lts
    restart: always
    ports:
      - "8008:8000"
    volumes:
      - ./client:/var/www/client
    tty: true
    working_dir: /var/www/client
    #command: npm install